### ISSUE TITLE
Fail on email check

### ISSUE THREAD

**Issue by puzanov** [D4Vinci/Cr3dOv3r#1]
python3.6 Cr3d0v3r.py email@example.com 
(I've tried using different emails, but see the same error)

```
[+] Checking email in public leaks...
Traceback (most recent call last):
  File "Cr3d0v3r.py", line 119, in <module>
    main()
  File "Cr3d0v3r.py", line 99, in main
    if ispwned.check(email):
  File "/Users/puzanov/src/Cr3dOv3r/ispwned.py", line 7, in check
    res = json.loads(req.text)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by D4Vinci** [comment]
The problem is with encoding,I will make a small commit to fix this ASAP.
Consider it solved.

**Comment by D4Vinci** [comment]
Released a hotfix check it out and reopen please if the problem stays!

**Comment by puzanov** [comment]
working, thanks
