### ISSUE TITLE
Link not found

### ISSUE THREAD

**Issue by Ekultek** [D4Vinci/Cr3dOv3r#11]
```
[+] Testing websites with one form (14)!
 -[   Vimeo   ] Login successful !
 -[  Ask.fm   ] Login unsuccessful!
Traceback (most recent call last):
  File "Cr3d0v3r.py", line 120, in <module>
    main()
  File "Cr3d0v3r.py", line 112, in main
    print( login( wd ,dic ,email ,pwd ) )
  File "Cr3d0v3r.py", line 44, in login
    browser.select_form(form)
  File "/usr/local/lib/python3.5/dist-packages/mechanicalsoup/stateful_browser.py", line 175, in select_form
    raise LinkNotFoundError()
mechanicalsoup.utils.LinkNotFoundError
```

**Comment by Ekultek** [comment]
duplicate of #2
