### ISSUE TITLE
Mechanicalsoup: Link not found Error

### ISSUE THREAD

**Issue by Ne02ptzero** [D4Vinci/Cr3dOv3r#2]
Hello,

I've tried your code, and i've run into an error on websites logins:
```
Traceback (most recent call last):
  File "Cr3d0v3r.py", line 119, in <module>
    main()
  File "Cr3d0v3r.py", line 111, in main
    print( login( wd ,dic ,email ,pwd ) )
  File "Cr3d0v3r.py", line 43, in login
    browser.select_form(form)
  File "/home/louis/.local/lib/python3.5/site-packages/mechanicalsoup/stateful_browser.py", line 175, in select_form
    raise LinkNotFoundError()
mechanicalsoup.utils.LinkNotFoundError
```

Here's a screenshot aswell:
![2017-11-14_829x237_scrot](https://user-images.githubusercontent.com/6032832/32774392-08b83380-c924-11e7-9aa9-6964d19b9133.png)

Cheers,

**Comment by Ekultek** [comment]
Same issue

**Comment by dNovel** [comment]
Same here.
`
[+] Testing websites with one form (14)!
 -[   Vimeo   ] Login successful !
 -[  Ask.fm   ] Login unsuccessful!
Traceback (most recent call last):
  File "Cr3d0v3r.py", line 120, in <module>
    main()
  File "Cr3d0v3r.py", line 112, in main
    print( login( wd ,dic ,email ,pwd ) )
  File "Cr3d0v3r.py", line 44, in login
    browser.select_form(form)
  File "/home/user/.local/lib/python3.5/site-packages/mechanicalsoup/stateful_browser.py", line 175, in select_form
    raise LinkNotFoundError()
mechanicalsoup.utils.LinkNotFoundError

`

**Comment by D4Vinci** [comment]
Ok fixing it ASAP

**Comment by D4Vinci** [comment]
Make sure at first you are running it with python3

**Comment by D4Vinci** [comment]
Released a hotfix check it out and reopen please if the problem stays!
