### ISSUE TITLE
OSX issue

### ISSUE THREAD

**Issue by Kaicastledine** [D4Vinci/Cr3dOv3r#37]
Version:0.3.1

Cloned- pip3 installed and run with python3 

```
[+] Checking email in public leaks...
Traceback (most recent call last):
  File "Cr3d0v3r.py", line 139, in <module>
    main()
  File "Cr3d0v3r.py", line 99, in main
    if ispwned.check_hackedEmails(email):
  File "/Users/kaic/Cr3dOv3r/Core/ispwned.py", line 9, in check_hackedEmails
    res = req.json()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by D4Vinci** [comment]
Yeah, that's because hacked-emails website just started to use Cloudflare today!
You can use the "-p" option till I figure out a solution.

**Comment by D4Vinci** [comment]
Contacted with company and waiting for reply

**Comment by D4Vinci** [comment]
They just fixed the problem and I tested it now and it's working fine.
reopen if there's any problem remaining :smile:

**Comment by Kaicastledine** [comment]
Perfect thank you !
