### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'select'

### ISSUE THREAD

**Issue by lukevanin** [D4Vinci/Cr3dOv3r#4]
MacOS 10.12.6 
Python 2.7.12

```
Traceback (most recent call last):
  File "Cr3d0v3r.py", line 119, in <module>
    main()
  File "Cr3d0v3r.py", line 111, in main
    print( login( wd ,dic ,email ,pwd ) )
  File "Cr3d0v3r.py", line 49, in login
    browser.select_form(form)
  File "/usr/local/lib/python2.7/site-packages/mechanicalsoup/stateful_browser.py", line 170, in select_form
    found_forms = self.__current_page.select(selector, limit=nr + 1)
AttributeError: 'NoneType' object has no attribute 'select'
```

**Comment by D4Vinci** [comment]
It's made for python 3 as said :3
