### ISSUE TITLE
Tool is awesome! But ..!

### ISSUE THREAD

**Issue by mayday77** [D4Vinci/Cr3dOv3r#46]
[+] Checking email in public leaks...
Traceback (most recent call last):
  File "Cr3d0v3r.py", line 164, in <module>
    main()
  File "Cr3d0v3r.py", line 138, in main
    if ispwned.check(email):
  File "/root/Downloads/Cr3dOv3r/ispwned.py", line 8, in check
    res = req.json()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by iNoSec** [comment]
i found how to solve this go on the PR for ispwned.py and make the change manually...

**Comment by mayday77** [comment]
"service_down"
message	"In accordance with the EU General Data Protection Regulation (GDPR), the Hacked-Emails API is no longer available. I am sorry for the effect GDPR has on your usage of this API, if you have questions please contact me directly using https://hacked-emails.com/contact"

**Comment by icepaule** [comment]
A really cool tool...!!!
But sorry guys, I need to change which part?
Wouldn't it be cool to change the git source so doing a pull request would solve the issue?  ;-)

Thx a lot
Marcus

**Comment by mayday77** [comment]
If you need a donation for coffee, lemme know  )

**Comment by D4Vinci** [comment]
Version 0.4 just released!
Fixed, added and improved many things.
Check it out!
