### ISSUE TITLE
🐛 Encoding issue

### ISSUE THREAD

**Issue by CosasDePuma** [D4Vinci/Cr3dOv3r#49]
When I execture the following command:
```sh
python Cr3d0v3r.py
```
The following error appears:
```py
Traceback (most recent call last):
  File "Cr3d0v3r.py", line 6, in <module>
    from Core import ispwned
  File "/GitHub/D4Vinci/Cr3dOv3r/Core/ispwned.py", line 40
SyntaxError: Non-ASCII character '\xe2' in file /GitHub/D4Vinci/Cr3dOv3r/Core/ispwned.py on line 40, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

Pls, add the following in the second line of `Core/ispwned.py`:
```py
# -*- encoding: utf-8 -*-
```

**Comment by D4Vinci** [comment]
Thanks for remembering me.
I added it in all files.
