### ISSUE TITLE
Python error

### ISSUE THREAD

**Issue by brtzli** [D4Vinci/Cr3dOv3r#53]
I used the following command:

python Cr3d0v3r.py email@email.it

The script can't be executed because of this:

Traceback (most recent call last):
  File "Cr3d0v3r.py", line 123, in <module>
    main()
  File "Cr3d0v3r.py", line 96, in main
    banner()
  File "C:\Users\Tony\Desktop\DB\TOOL_Cr3dOv3r-master\Core\utils.py", line 22, in banner
    banner = open(os.path.join("Data","banners.txt")).read()
  File "C:\Users\Tony\AppData\Local\Programs\Python\Python36\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 972: character maps to <undefined>

**Comment by musiyenko** [comment]
Add the following lines under from `.color import *`
```python
import sys
reload(sys)
sys.setdefaultencoding('utf8')
```

**Comment by D4Vinci** [comment]
This problem happens only in Python 2 but Python 3 has a default encoding.
Anyway #54 fixed and it and I made a patch for this PR so it works on both 2 and 3 will be pushed ASAP with the others fixes.
