### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by axelarator** [D4Vinci/Cr3dOv3r#56]
Plaintext password was found for 
Name : neopets

```
Traceback (most recent call last):
  File "Cr3d0v3r.py", line 123, in <module>
    main()
  File "Cr3d0v3r.py", line 99, in main
    ispwned.parse_data(email,args.np)
  File "/root/Cr3dov3r/Core/ispwned.py", line 41, in parse_data
    print(C+" │"+B+"  └──── "+W+pp.split(":")[1])
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 6: ordinal not in range(128)

```

**Comment by D4Vinci** [comment]
Which platform you are using?

**Comment by D4Vinci** [comment]
Fixed it, thanks.
