### ISSUE TITLE
ValueError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by zdavatz** [D4Vinci/Cr3dOv3r#7]
Tried to use this, but I am getting the following error with Python 3.4. on Linux (Gentoo).

```
[+] Checking email in public leaks...
Traceback (most recent call last):
  File "./Cr3d0v3r.py", line 119, in <module>
    main()
  File "./Cr3d0v3r.py", line 100, in main
    to_print = ispwned.parse_data(email)
  File "/home/zeno/.software/Cr3dOv3r/ispwned.py", line 18, in parse_data
    data         = check(email,"His shit :D")
  File "/home/zeno/.software/Cr3dOv3r/ispwned.py", line 7, in check
    res = json.loads(req.text)
  File "/usr/lib64/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
```

**Comment by zdavatz** [comment]
I did install all the requirements:
```
~/.software/Cr3dOv3r> /usr/bin/pip3.4 install -r requirements.txt
Requirement already satisfied: mechanicalsoup>=0.9 in /usr/lib64/python3.4/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied: requests>=2.0 in /usr/lib64/python3.4/site-packages (from mechanicalsoup>=0.9->-r requirements.txt (line 1))
Requirement already satisfied: beautifulsoup4 in /usr/lib64/python3.4/site-packages (from mechanicalsoup>=0.9->-r requirements.txt (line 1))
Requirement already satisfied: six>=1.4 in /usr/lib64/python3.4/site-packages (from mechanicalsoup>=0.9->-r requirements.txt (line 1))
Requirement already satisfied: lxml in /usr/lib64/python3.4/site-packages (from mechanicalsoup>=0.9->-r requirements.txt (line 1))
```

**Comment by D4Vinci** [comment]
The problem is with encoding,I will make a small commit to fix this ASAP.
Consider it solved.

**Comment by D4Vinci** [comment]
Released a hotfix check it out and reopen please if the problem stays!

**Comment by zdavatz** [comment]
works!
