### ISSUE TITLE
'encoding' is an invalid keyword

### ISSUE THREAD

**Issue by CarloMartini** [D4Vinci/Cr3dOv3r#73]
Hello, when I execute the script (all deps are satisfied) I only have this error message:

```
Traceback (most recent call last):
  File "Cr3d0v3r.py", line 151, in <module>
    main()
  File "Cr3d0v3r.py", line 124, in main
    banner()
  File "/home/elan42/Cr3dOv3r/Core/utils.py", line 22, in banner
    banner = open(os.path.join("Data","banners.txt"), encoding="utf8").read()
TypeError: 'encoding' is an invalid keyword argument for this function
```

My system:

Linux elan42-mint 4.15.0-29-generic #31~16.04.1-Ubuntu SMP Wed Jul 18 08:54:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by vishwenga** [comment]
i had the same issue, but when i ran with python3 it worked.
